### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Dreeam-qwq** [Elytrium/LimboAPI#13]
error when load the plugin
```
[21:41:08 ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.NullPointerException: Cannot invoke "java.lang.Short.shortValue()" because the return value of "java.util.Map.get(Object)" is null
        at net.elytrium.limboapi.server.world.SimpleItem.getId(SimpleItem.java:54) ~[?:?]
        at net.elytrium.limboapi.server.world.SimpleItem.getId(SimpleItem.java:50) ~[?:?]
        at net.elytrium.limboapi.protocol.packet.SetSlot.encode(SetSlot.java:64) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.encodePacket(PreparedPacketImpl.java:106) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:78) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:57) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:37) ~[?:?]
        at net.elytrium.limbofilter.cache.CachedPackets.createPackets(CachedPackets.java:78) ~[?:?]
        at net.elytrium.limbofilter.FilterPlugin.reload(FilterPlugin.java:115) ~[?:?]
        at net.elytrium.limbofilter.FilterPlugin.onProxyInitialization(FilterPlugin.java:102) ~[?:?]
        at net.elytrium.limbofilter.Lmbda$7.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-proxy-3.0.2-SNAPSHOT-all.jar:3.0.2-SNAPSHOT (git-e70eac1d-bunknown)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity-proxy-3.0.2-SNAPSHOT-all.jar:3.0.2-SNAPSHOT (git-e70eac1d-bunknown)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity-proxy-3.0.2-SNAPSHOT-all.jar:3.0.2-SNAPSHOT (git-e70eac1d-bunknown)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Dreeam-qwq** [comment]
> ?

yes

**Comment by Dreeam-qwq** [comment]
> Are you using latest version from actions?

yes

**Comment by mdxd44** [comment]
> 
> 
> > Are you using latest version from actions?
> 
> yes

try this version https://github.com/Elytrium/LimboAPI/actions/runs/1345880854

**Comment by Dreeam-qwq** [comment]
> > > Are you using latest version from actions?
> > 
> > 
> > yes
> 
> try this version https://github.com/Elytrium/LimboAPI/actions/runs/1345880854

new error https://paste.gg/p/anonymous/7861036197404338984870209ce3af33

**Comment by mdxd44** [comment]
> 
> 
> > > > Are you using latest version from actions?
> > > 
> > > 
> > > yes
> > 
> > 
> > try this version https://github.com/Elytrium/LimboAPI/actions/runs/1345880854
> 
> new error https://paste.gg/p/anonymous/7861036197404338984870209ce3af33

try this https://github.com/Elytrium/LimboAPI/actions/runs/1284513676

**Comment by Dreeam-qwq** [comment]
i use the 1.18snapshot branch of velocity, and the latest limboapi can't work 
https://ci.velocitypowered.com/job/velocity-1.18-snapshot-build/

on velocity 3.0.x works well

**Comment by mdxd44** [comment]
> 
> 
> i used the 1.18 snapshot branch of velocity, and the latest limboapi can't work https://ci.velocitypowered.com/job/velocity-1.18-snapshot-build/
> 
> on velocity 3.0.x works well

we currently don't have 1.18 mappings for items and blocks

**Comment by mdxd44** [comment]
use the latest velocity build for 1.17
