### ISSUE TITLE
[BUG] Can't join to the server on the latest velocity

### ISSUE THREAD

**Issue by EpicPlayerA10** [Elytrium/LimboAPI#132]
**Describe the bug**
Can't join to the server on the latest velocity. In console it shows this error:
```
[14:40:12 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.elytrium.limboapi.injection.login.LoginListener$$Lambda$2440/0x00007f039c8da7f8@6226f8b0
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboapi.injection.login.LoginListener.lambda$hookLoginSession$2(LoginListener.java:225) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.connection.MinecraftConnection.write(java.lang.Object)'
        at net.elytrium.limboapi.injection.login.LoginListener.lambda$hookLoginSession$2(LoginListener.java:165) ~[?:?]
        ... 8 more
```

**To Reproduce**
1. Install only LimboAPI
2. Join to the proxy

**Expected behavior**
It should join to the server and not throw an error.

**Screenshots**

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI Release 1.1.18 Hotfix 2, downloaded from https://github.com/Elytrium/LimboAPI/releases/download/1.1.18/limboapi-1.1.18.jar

 - /velocity dump link [velocity-dump-2024-01-12-15-57-24.json](https://github.com/Elytrium/LimboAPI/files/13920500/velocity-dump-2024-01-12-15-57-24.json)

**Additional context**
It happens because of this commit https://github.com/PaperMC/velocity/commit/08c03aaea2bf69673a739494e7d8884d31c5002d . It changes a return value of `write` method.

Simple plugin rebuild with the latest velocity natives will fix this issue.

**Comment by TheFaik** [comment]
+
