### ISSUE TITLE
[BUG] NoSuchMethodError: can't connect to the server

### ISSUE THREAD

**Issue by comendantmc** [Elytrium/LimboAPI#135]
**Describe the bug**
When running the LimboAPI built from the master branch you can't connect to the server.

**To Reproduce**
1. Clone the repo
2. ```./gradlew build```
3. Take the jar from ```plugin/build/libs```

**Expected behavior**
I should be able to connect to the server

**Error**

```
[06:56:54 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.elytrium.limboapi.injection.login.LoginListener$$Lambda$833/0x00007fe7b8427310@4cd4ba3f
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboapi.injection.login.LoginListener.lambda$hookLoginSession$1(LoginListener.java:218) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.connection.MinecraftConnection.write(java.lang.Object)'
        at net.elytrium.limboapi.injection.login.LoginListener.lambda$hookLoginSession$1(LoginListener.java:164) ~[?:?]
        ... 8 more
```

**Server Info:**
 - LimboAPI master (commit 655662f782f79bc1eb5f74b2540ddd1214067ced)
 - velocity-3.3.0-SNAPSHOT-320
 - /velocity dump link: https://hastebin.com/share/yobamutapo.json

**Client Info:**
- Minecraft 1.19.4

**Comment by hevav** [comment]
purge gradle cache
