### ISSUE TITLE
[BUG] error Velocity 3.3.0-331

### ISSUE THREAD

**Issue by TheFaik** [Elytrium/LimboAPI#137]
Can't create plugin limboapi
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: ReflectionException: An unexpected internal error was caught during the reflection operations.
  at LimboAPI.<init>(LimboAPI.java:154)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboAPI

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
LimboAPI:             "net.elytrium.limboapi.LimboAPI"
ReflectionException:  "net.elytrium.commons.utils.reflection.ReflectionException"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
Caused by: net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboapi.LimboAPI.<init>(LimboAPI.java:192) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$1811c7c.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$1811c7c.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        ... 6 more
Caused by: java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/LegacyPlayerListItem
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.<init>(LimboAPI.java:187) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$1811c7c.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$1811c7c.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.LegacyPlayerListItem
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.<init>(LimboAPI.java:187) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$1811c7c.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$1811c7c.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        ... 6 more
[18:09:45 ERROR]: Can't create plugin limboauth
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboAuth.<init>(LimboAuth.java:184)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboAuth

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
LimboAuth:              "net.elytrium.limboauth.LimboAuth"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.<init>(LimboAuth.java:194) ~[?:?]
        at net.elytrium.limboauth.LimboAuth$$FastClassByGuice$$19827d0.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboauth.LimboAuth$$FastClassByGuice$$19827d0.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        ... 6 more
[18:09:45 ERROR]: Can't create plugin limbofilter
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboFilter.<init>(LimboFilter.java:122)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboFilter

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
LimboFilter:            "net.elytrium.limbofilter.LimboFilter"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.<init>(LimboFilter.java:131) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter$$FastClassByGuice$$1a8be7b.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter$$FastClassByGuice$$1a8be7b.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        ... 6 more
[18:09:45 ERROR]: Can't create plugin limboqueue
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboQueue.<init>(LimboQueue.java:75)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboQueue

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
LimboQueue:             "net.elytrium.limboqueue.LimboQueue"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at net.elytrium.limboqueue.LimboQueue.<init>(LimboQueue.java:83) ~[?:?]
        at net.elytrium.limboqueue.LimboQueue$$FastClassByGuice$$1b34afd.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboqueue.LimboQueue$$FastClassByGuice$$1b34afd.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        ... 6 more
[18:09:45 ERROR]: Can't create plugin limboreconnect
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboReconnect.<init>(LimboReconnect.java:74)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboReconnect

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
LimboReconnect:         "net.elytrium.limboreconnect.LimboReconnect"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at net.elytrium.limboreconnect.LimboReconnect.<init>(LimboReconnect.java:87) ~[?:?]
        at net.elytrium.limboreconnect.LimboReconnect$$FastClassByGuice$$1c5cd2b.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboreconnect.LimboReconnect$$FastClassByGuice$$1c5cd2b.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-35137df7-b331)]
        ... 6 more

**Comment by DHCPCD9** [comment]
Downgrade velocity to b328

**Comment by TheFaik** [comment]
> Понизить скорость до b328

I did so, but it's a shame that LimboAPI does not support the latest version of Velocity...
