### ISSUE TITLE
[BUG] какаята фигня с limboapi и дополнениями

### ISSUE THREAD

**Issue by Perets2207** [Elytrium/LimboAPI#145]
**Describe the bug**
При установке limboapi с последнего удачного билда в actions и плагинов auth/reconnect/filter/hub/queue вылазит ошибка

**To Reproduce**
установи выше описанные плагины с последних билдов в actions

**Server Info (please complete the following information):**
LimboAPI (не скомпилился когда компилил сам)
LimboAuth (скомпилился когда компилил сам)
LimboFilter (скомпилился когда компилил сам)
LimboHub (не скомпилился когда компилил сам)
LimboAuth social addon (скомпилился когда компилил сам)
LimboQueue (скомпилился когда компилил сам)
limboreconnect (скомпилился когда компилил сам)
fastmotd (не скомпилился когда компилил сам)
velocity tools (скомпилился когда компилил сам)
skinsrestorer
viaversion
viabackwards
luckperms
spark

`[16:03:32 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
java.lang.IllegalAccessError: class net.elytrium.limboapi.server.LimboImpl tried to access private method 'void com.velocitypowered.proxy.protocol.packet.config.StartUpdatePacket.<init>()' (net.elytrium.limboapi.server.LimboImpl is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @1686f0b4; com.velocitypowered.proxy.protocol.packet.config.StartUpdatePacket is in unnamed module of loader 'app')
        at net.elytrium.limboapi.server.LimboImpl.refresh(LimboImpl.java:228) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.<init>(LimboImpl.java:178) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.createLimbo(LimboAPI.java:380) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:385) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:212) ~[?:?]
        at net.elytrium.limboauth.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-15897c52-b357)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]`
подобное во всех вышеописанных плагинах (которые описаны в **Describe the bug**)

и прошу разобраться почему при компиле некоторые плагины не скомпилились (компилил через github actions)

**Comment by TheFaik** [comment]
+++

**Comment by Perets2207** [comment]
решение (у меня сработало ) в воркфлоу в бранче 1.1.21 ставим в on: триггер workflow_dispatch:
и запускаем воркфлоу из этого бранча
