### ISSUE TITLE
[BUG] Couldn't pass ProxyInitializeEvent to limboauth.

### ISSUE THREAD

**Issue by Hlorum** [Elytrium/LimboAPI#147]
Couldn't pass ProxyInitializeEvent to limboauth.

1. Install velocity-3.3.0-SNAPSHOT-358.jar
2. Install limboapi-1.1.21.jar + limboauth-1.1.13.jar.
3. Start the server.

 - /velocity dump
 https://drive.google.com/file/d/1zFpKIXY8p1Ih-VO84Fzw8AsdIhIavyiN/view?usp=drive_link

Log: https://logs.hosting-minecraft.pro/akiyibajic

[18:14:21 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
        at net.elytrium.limboauth.listener.AuthListener.<clinit>(AuthListener.java:176) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:387) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerLogin
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 10 more

**Comment by SkyWatcher2019** [comment]
Download the latest LimboAuth (https://github.com/Elytrium/LimboAuth/actions/runs/7670771184)
