### ISSUE TITLE
[BUG] ERROR Velocity-3.3.0-360

### ISSUE THREAD

**Issue by TheFaik** [Elytrium/LimboAPI#148]
Couldn't pass ProxyInitializeEvent to limboapi
java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.protocol.packet.DisconnectPacket com.velocitypowered.proxy.protocol.packet.DisconnectPacket.create(net.kyori.adventure.text.Component, com.velocitypowered.api.network.ProtocolVersion, boolean)'
        at net.elytrium.limboapi.server.CachedPackets.createDisconnectPacket(CachedPackets.java:62) ~[?:?]
        at net.elytrium.limboapi.server.CachedPackets.lambda$createPackets$0(CachedPackets.java:48) ~[?:?]
        at net.elytrium.limboapi.thirdparty.fastprepare.PreparedPacket.prepare(PreparedPacket.java:133) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:89) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:26) ~[?:?]
        at net.elytrium.limboapi.thirdparty.fastprepare.PreparedPacket.prepare(PreparedPacket.java:119) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:79) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:26) ~[?:?]
        at net.elytrium.limboapi.server.CachedPackets.createPackets(CachedPackets.java:48) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.reload(LimboAPI.java:280) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.onProxyInitialization(LimboAPI.java:248) ~[?:?]
        at net.elytrium.limboapi.Lmbda$17.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2cf18b0a-b360)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2cf18b0a-b360)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2cf18b0a-b360)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
[18:43:32 INFO] [limbofilter]: Current captcha generator settings will consume 0.08GB RAM normally and 0.15GB RAM on reloads
[18:43:32 INFO] [limbofilter]: Modify the config to decrease RAM consumptio

**Comment by SashaGoncharov19** [comment]
limboapi don't provide support for MC 1.20.4 for now. I have the same error.

**Comment by akbe2020** [comment]
The same

**Comment by luminescar** [comment]
same
