### ISSUE TITLE
[BUG] Error When I First Join After Restart

### ISSUE THREAD

**Issue by whiskeytr** [Elytrium/LimboAPI#164]
**Describe the bug**
A clear and concise description of the bug.
When I restart the server for first join getting a error.
**To Reproduce**
1. Set '...' in config to '...'
2. Do in game '....'
3. See error
First join after restart.
**Expected behavior**

**Screenshots**

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - [e.g. LimboAPI 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]
 - [e.g. LimboFilter 1.0.3-rc3, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]
Latest version of Limbo plugins and velocity.
 - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]
https://paste.gg/p/anonymous/16854485da3e43a381c988e03500d6b4/files/028323c00cd0483899fdd4f0806a64cd/raw
**Additional context**
 `[19:33:19] [Netty NIO Worker #12/DEBUG] [aauth]: Adding new player to limbo -> WhiskeyTR
[19:33:26] [Netty NIO Worker #16/DEBUG] [aauth]: Adding new player to limbo -> WhiskeyTR
[19:33:26] [Netty NIO Worker #16/INFO] [limboapi]: WhiskeyTR (127.0.0.1/127.0.0.1:49754) has connected to the AAuth Limbo
[19:33:38] [Netty NIO Worker #12/INFO] [limboapi]: WhiskeyTR (127.0.0.1/127.0.0.1:49745) has connected to the AAuth Limbo
[19:33:38] [Netty NIO Worker #12/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [initial connection] 127.0.0.1/127.0.0.1:49745: exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl@1f89da04
java.io.IOException: Kurulan bir bağlantı, ana makinenizdeki yazılım tarafından iptal edildi
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:46) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:340) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:294) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:269) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:425) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by UserNugget** [comment]
It seems that client closed connection for some reason.
How client disconnects? Are there any errors in the client logs?

**Comment by zikehalil3535** [comment]
> It seems that client closed connection for some reason. How client disconnects? Are there any errors in the client logs?

I dont know this causing after update the plugin.
![image](https://github.com/user-attachments/assets/5d5eedcf-dc08-4fef-a111-93d19910e187)

**Comment by UserNugget** [comment]
Oh, im asking about clientside view of this error, like client logs and what disconnect message client shows.

**Comment by zikehalil3535** [comment]
> Oh, im asking about clientside view of this error, like client logs and what disconnect message client shows.

Actually there is no problem in the clientside log, it doesn't kick me anyway, it connects me to my main server but gives an error every time, this occurred after the latest version LimboAPI update.

**Comment by zikehalil3535** [comment]
> Oh, im asking about clientside view of this error, like client logs and what disconnect message client shows.

Here is the client side log:
https://paste.gg/p/anonymous/10c45bdb5d7c42a486aec73fdd872135/files/a8a7fad3661d43618efd88ad0a498ef9/raw

**Comment by levitskyyy** [comment]
this problem only exists on new versions of velocity

**Comment by levitskyyy** [comment]
Duplicate of #167

**Comment by whiskeytr** [comment]
Fixed.
