### ISSUE TITLE
[BUG] LimboReconnect not work with new PacketEvents and LimboAPI

### ISSUE THREAD

**Issue by WhyYum** [Elytrium/LimboAPI#172]
**Describe the bug**
After updating PacketEvents plugins to 2.6.0 from 2.4.1-SNAPSHOT (fix for LimboAPI) and LimboAPI to 1.1.24 from 1.1.27 (fix for PacketEvents), LimboReconnect stopped working. Both with old version 1.1.4 and with new version 1.1.7

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
![image](https://github.com/user-attachments/assets/89995553-7ab7-41fb-b0e2-3776593e0516)

**Server Info (please complete the following information):**
 Velocity 3.4.0
PacketEvents 2.6.0
LimboAPI 1.1.27
LimboReconnect 1.1.7

 - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]

**Additional context**
-

```[21:12:01 ERROR]: [connected player] WhyYum (/127.0.0.1:19571): exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl@5cccc737
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unable to find id for packet of type net.elytrium.limboapi.protocol.packets.s2c.ChangeGameStatePacket in CLIENTBOUND protocol 1.20.2 phase PLAY
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at net.elytrium.limboapi.thirdparty.fastprepare.handler.PreparedPacketEncoder.write(PreparedPacketEncoder.java:89) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:964) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:300) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at net.elytrium.limboapi.server.LimboPlayerImpl.writePacket(LimboPlayerImpl.java:79) ~[?:?]
        at net.elytrium.limboapi.server.LimboPlayerImpl.setGameMode(LimboPlayerImpl.java:220) ~[?:?]
        at net.elytrium.limboreconnect.handler.ReconnectHandler.onSpawn(ReconnectHandler.java:60) ~[?:?]
        at net.elytrium.limboapi.server.LimboSessionHandlerImpl.onSpawn(LimboSessionHandlerImpl.java:167) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.onSpawn(LimboImpl.java:607) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.spawnPlayerLocal(LimboImpl.java:458) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.lambda$spawnPlayerLocal$18(LimboImpl.java:547) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find id for packet of type net.elytrium.limboapi.protocol.packets.s2c.ChangeGameStatePacket in CLIENTBOUND protocol 1.20.2 phase PLAY
        at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry$ProtocolRegistry.getPacketId(StateRegistry.java:915) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:52) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.4.0-SNAPSHOT (git-9cfcfcf2-b451)]
        ... 27 more```

**Comment by mdxd44** [comment]
have you tried to set compatibility-mode to true?

**Comment by WhyYum** [comment]
> have you tried to set compatibility-mode to true in LimboAPI config?
Yes.
save-uncompressed-packets: true
compatibility-mode: true
The error was with both enabled, without compatibility-mode enabled it wouldn't let me into the server because of PacketEvents

**Comment by Brickgard** [comment]
This has been the behavior I have seen since as far back as packetevents 2.5.0ish, as mentioned in the OP.
There's been multiple talks about it being fixed, such as with compatibility-mode or through packetevent updates, but unfortunately I have yet to see a combination that makes LimboReconnect function on these recent versions.
