### ISSUE TITLE
[ENHANCEMENT] Improve documentation for developers

### ISSUE THREAD

**Issue by AlexInCube** [Elytrium/LimboAPI#174]
**Describe the feature you'd like to have implemented**
I would like to see methods described in the code or documentation, and a primitive example of how to create virtual worlds.

**Is your feature request related to an existing problem? Please describe.**
Without documentation, you have to sit and research the LimboAuth plugin for a very long time to try to understand how to work with LimboAPI. 
But in LimboAuth there is a lot of code and it is without comments, you have to sit with a debugger to understand something in it.

**Additional context**
All we have from the code samples are three lines from README.md

**Comment by mdxd44** [comment]
Actually, i made one, but it was a long time ago, and i only shared it on discord
[limboexample_test.zip](https://github.com/user-attachments/files/17985173/limboexample_test.zip)

I will later create a separate submodule or repository with a similar project that includes an example of how to use most of the provided API

**Comment by AlexInCube** [comment]
I have error: java.lang.NullPointerException: Cannot read field "REDUCED_DEBUG_INFO" because "net.elytrium.limboapi.Settings.IMP.MAIN" is null

**Comment by mdxd44** [comment]
> I have error: java.lang.NullPointerException: Cannot read field "REDUCED_DEBUG_INFO" because "net.elytrium.limboapi.Settings.IMP.MAIN" is null

The error you provided doesn't provide much information, please share the full error log

**Comment by AlexInCube** [comment]
> > I have error: java.lang.NullPointerException: Cannot read field "REDUCED_DEBUG_INFO" because "net.elytrium.limboapi.Settings.IMP.MAIN" is null
> 
> The error you provided doesn't provide much information, please share the full error log

I have IMP.MAIN null when  `this.limboFactory.createVirtualWorld()` is executed.

```java
public class LimboHandler {
    private final ProxyServer server;
    private final Logger logger;
    private final LimboFactory limboFactory;
    public Limbo virtualServer;

    public LimboHandler(ProxyServer server, Logger logger) {
        this.server = server;
        this.logger = logger;
        this.limboFactory = (LimboFactory) this.server.getPluginManager().getPlugin("limboapi").flatMap(PluginContainer::getInstance).orElseThrow();
    }

    @Subscribe
    public void onLoginLimboRegister(LoginLimboRegisterEvent event) {
        logger.info("pizdec");
    }

    public void reload(){
        VirtualWorld world = this.limboFactory.createVirtualWorld(
                Dimension.OVERWORLD,
                17, 32, 15,
                0F, 0F
        );
        //new SchematicFile(this.getClass().getResourceAsStream("/limbo.schematic")).toWorld(this.factory, world, 0, 0, 0);
        this.virtualServer = this.limboFactory.createLimbo(world);
    }
}
```

My main plugin class

```java
public class Auth {
    private GrpcClientHandler grpcClientHandler;
    private final ProxyServer proxyServer;
    private final Logger logger;
    private ConfigHandler configHandler;
    private LimboHandler limboHandler;

    @Inject
    public EximiaAuth(ProxyServer proxyServer, Logger logger) {
        this.proxyServer = proxyServer;
        this.logger = logger;
    }

    @Subscribe
    public void onProxyInitialization(ProxyInitializeEvent event) {
        try {
            this.limboHandler = new LimboHandler(proxyServer, logger);
            limboHandler.reload();
            // Create/read config.yml
            this.configHandler = new ConfigHandler();
            // Connect to GRPC microservice
            this.grpcClientHandler = new GrpcClientHandler(
                    this.logger,
                    new GrpcOptions(
                            configHandler.getIpGRPC(),
                            configHandler.getPortGRPC()
                    )
            );
        } catch (Exception e) {
            e.printStackTrace();
        }

        CommandManager commandManager = proxyServer.getCommandManager();
        CommandMeta commandMeta = commandManager.metaBuilder("register")
                .plugin(this)
                .build();

        BrigadierCommand commandToRegister = RegisterCommand.createBrigadierCommand(this.proxyServer);
        commandManager.register(commandMeta, commandToRegister);
    }

    @Subscribe(order = PostOrder.LATE)
    public void onLogin(LoginLimboRegisterEvent event) {
        event.addCallback(() -> this.limboHandler.virtualServer.spawnPlayer(event.getPlayer(), new LimboSessionHandler()));
    }
}
```

Full error
```
[00:44:09 INFO]: Booting up Velocity 3.4.0-SNAPSHOT (git-be5f0ace-b453)...
[00:44:09 INFO]: Loading localizations...
[00:44:09 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[00:44:09 WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support!
[00:44:09 INFO]: Loading plugins...
[00:44:09 INFO]: Loaded plugin eximiaauth 0.1.0 by AlexInCube
[00:44:10 WARN] [limboapi]: Current LimboAPI version doesn't support current Velocity version (protocol version numbers: supported - 768, velocity - 769)
[00:44:10 WARN] [limboapi]: Please update LimboAPI (https://github.com/Elytrium/LimboAPI/releases). LimboAPI support: https://ely.su/discord
[00:44:10 INFO] [limboapi]: Initializing Simple Virtual World system...
[00:44:10 INFO] [limboapi]: Hooking into PlayerList/UpsertPlayerInfo and StateRegistry...
[00:44:10 INFO]: Loaded plugin limboapi 1.1.27 by Elytrium (https://elytrium.net/)
[00:44:10 INFO]: Loaded plugin luckperms 5.4.146 by Luck
[00:44:10 INFO]: Loaded 4 plugins
[00:44:11 INFO]:         __    
[00:44:11 INFO]:   |    |__)   LuckPerms v5.4.146
[00:44:11 INFO]:   |___ |      Running on Velocity - Velocity
[00:44:11 INFO]: 
[00:44:11 INFO] [luckperms]: Loading configuration...
[00:44:11 INFO] [luckperms]: Loading storage provider... [H2]
[00:44:12 INFO] [luckperms]: Loading internal permission managers...
[00:44:12 INFO] [luckperms]: Performing initial data load...
[00:44:12 INFO] [luckperms]: Successfully enabled. (took 1272ms)
[00:44:12 ERROR]: java.lang.NullPointerException: Cannot read field "REDUCED_DEBUG_INFO" because "net.elytrium.limboapi.Settings.IMP.MAIN" is null
[00:44:12 ERROR]: 	at net.elytrium.limboapi.server.LimboImpl.<init>(LimboImpl.java:175)
[00:44:12 ERROR]: 	at net.elytrium.limboapi.LimboAPI.createLimbo(LimboAPI.java:397)
[00:44:12 ERROR]: 	at org.alexincube.eximiaauth.eximiaAuth.handlers.limbo.LimboHandler.reload(LimboHandler.java:40)
[00:44:12 ERROR]: 	at org.alexincube.eximiaauth.eximiaAuth.EximiaAuth.onProxyInitialization(EximiaAuth.java:40)
[00:44:12 ERROR]: 	at org.alexincube.eximiaauth.eximiaAuth.Lmbda$2.execute(Unknown Source)
[00:44:12 ERROR]: 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[00:44:12 ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676)
[00:44:12 ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541)
[00:44:12 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:44:12 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:44:12 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:44:12 WARN] [limboapi]: ************* FIRST LAUNCH *************
[00:44:12 WARN] [limboapi]: Thanks for installing LimboAPI!
[00:44:12 WARN] [limboapi]: (C) 2021 - 2024 Elytrium
[00:44:12 WARN] [limboapi]: 
[00:44:12 WARN] [limboapi]: Check out our plugins here: https://ely.su/github <3
[00:44:12 WARN] [limboapi]: Discord: https://ely.su/discord
[00:44:12 WARN] [limboapi]: ****************************************
[00:44:12 INFO] [limboapi]: Creating and preparing packets...
[00:44:12 INFO] [limboapi]: Loaded!
[00:44:12 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[00:44:12 INFO]: Done (4.14s)!
```

**Comment by AlexInCube** [comment]
> > I have error: java.lang.NullPointerException: Cannot read field "REDUCED_DEBUG_INFO" because "net.elytrium.limboapi.Settings.IMP.MAIN" is null
> 
> The error you provided doesn't provide much information, please share the full error log

I am resolve this issue by adding dependencies field to @Plugin
```
dependencies = {
      @Dependency(id = "limboapi")
}
```

**Comment by hevav** [comment]
@AlexInCube Velocity schedules the events in alphabetical order - events from "Auth" preceed events from the "LimboAPI" ('A' < 'L'). Try adding @Subscribe(order = PostOrder.LAST) on ProxyInitializeEvent.

**Comment by AlexInCube** [comment]
I don't understand yet how to properly register commands in LimboApi. From Velocity documentation, I am register command using Brigadier. https://docs.papermc.io/velocity/dev/command-api#brigadiercommand

When i join to Velocity Minecraft server, i have autocomplete for /register command. But command dont executes, also i give myself "register.permission" using plugin LuckPerms.

Register Command class:
```java
public class RegisterCommand {
    public static BrigadierCommand createBrigadierCommand(final ProxyServer proxyServer){
        LiteralCommandNode<CommandSource> helloNode = BrigadierCommand.literalArgumentBuilder("register")
                .requires(commandSource -> commandSource.hasPermission("register.permission"))
                .executes(commandContext -> {
                    CommandSource source = commandContext.getSource();

                    System.out.print("Register");

                    return Command.SINGLE_SUCCESS;
                })
                .build();

        return new BrigadierCommand(helloNode);
    }
}
```

In main plugin class, event onProxyInitialization

```java
CommandManager commandManager = proxyServer.getCommandManager();
        CommandMeta commandMeta = commandManager.metaBuilder("register")
                .plugin(this)
                .build();

        BrigadierCommand commandToRegister = RegisterCommand.createBrigadierCommand(this.proxyServer);
        commandManager.register(commandMeta, commandToRegister);
```

Creating limbo world:
```java
public void reload(){
        VirtualWorld world = this.limboFactory.createVirtualWorld(
                Dimension.OVERWORLD,
                17, 32, 15,
                0F, 0F
        );

        List<String> aliases = new ArrayList<>(Collections.emptyList());
        aliases.add("register");
        //new SchematicFile(this.getClass().getResourceAsStream("/limbo.schematic")).toWorld(this.factory, world, 0, 0, 0);
        this.virtualServer = this.limboFactory.createLimbo(world)
                .setGameMode(GameMode.SURVIVAL)
                .registerCommand(new LimboCommandMeta(aliases));
                //.registerCommand((LimboCommandMeta) this.server.getCommandManager().getCommandMeta("login"));
    }
```

**Comment by mdxd44** [comment]
Currently, command registration exists solely to inform the client that your command exists. The actual processing needs to be moved to the LimboSessionHandler#onChat(String) method.

**Comment by AlexInCube** [comment]
I'm trying to figure out how to disconnect or join players to the server. In my researching, i write this code, it works, but something seems wrong to me. That .disconnect() function do not disconnect, but connect player to a Paper server.

```java
public class LimboCustomSessionHandler implements LimboSessionHandler {
    private final Player proxyPlayer;
    @MonotonicNonNull
    private LimboPlayer limboPlayer;

    private static final Serializer serializer = new Serializer(Objects.requireNonNull(Serializers.LEGACY_AMPERSAND.getSerializer()));
    private static final Component loginWrongPasswordKick = serializer.deserialize("**** you");

    public LimboCustomSessionHandler(Player proxyPlayer){
        this.proxyPlayer = proxyPlayer;
    }

    @Override
    public void onSpawn(Limbo server, LimboPlayer player) {
        player.disableFalling();
        this.limboPlayer = player;
    }

    @Override
    public void onChat(String chat) {
        // This code disconnects you from the server completely
        if (chat.equals("go back i wan't to be monke")) {
            this.proxyPlayer.disconnect(loginWrongPasswordKick);
        }

        // This code connects you to a Paper server
        if (chat.equals("login")) {
            this.limboPlayer.disconnect();
        }
    }
}
```

**Comment by mdxd44** [comment]
LimboPlayer#disconnect disconnects the player from the current limbo, while Player#disconnect disconnects the player from the proxy

**Comment by AlexInCube** [comment]
> LimboPlayer#disconnect disconnects the player from the current limbo, while Player#disconnect disconnects the player from the proxy

Well, if everything is OK, then I'll keep using this code.

**Comment by UserNugget** [comment]
Should be working fine since https://github.com/Elytrium/LimboAPI/commit/b1a8e4787f82b55707589823afd71b9aaddce2f9

**Comment by Hellscaped** [comment]
> Should be working fine since [b1a8e47](https://github.com/Elytrium/LimboAPI/commit/b1a8e4787f82b55707589823afd71b9aaddce2f9)

Yeah, its showing as just a map item: not the actual image. I'm on 1.1.27-dev, I'll update my api jar and lets see

**Comment by Hellscaped** [comment]
updating works
