### ISSUE TITLE
player can join but limboauth does not make the person need to login(basicly just join to the server without needing to login)

### ISSUE THREAD

**Issue by Garuda2703** [Elytrium/LimboAPI#18]
[18:53:30] [Velocity Async Event Executor - #3/ERROR]: Couldn't pass GameProfileRequestEvent to limboapi
java.lang.IllegalArgumentException: Can not set final com.velocitypowered.proxy.connection.MinecraftConnection field com.velocitypowered.proxy.connection.client.InitialInboundConnection.connection to com.velocitypowered.proxy.connection.client.LoginInboundConnection
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:419) ~[?:?]
        at net.elytrium.limboapi.injection.login.LoginListener.hookLoginSession(LoginListener.java:134) ~[?:?]
        at net.elytrium.limboapi.injection.login.Lmbda$516.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.0-SNAPSHOT (git-d3b3ef23-b92)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.0-SNAPSHOT (git-d3b3ef23-b92)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.0-SNAPSHOT (git-d3b3ef23-b92)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by hevav** [comment]
Velocity 3.1.0 is not supported in the release version of LimboAPI
LimboAPI just cannot inject itself into the player's connection, that's why LimboAuth doesn't work either
It is already fixed in the dev version of LimboAPI, you can download it in the ["Actions"](https://github.com/Elytrium/LimboAPI/actions) tab of this project

**Comment by Garuda2703** [comment]
new error: now it stuck on this 
![image](https://user-images.githubusercontent.com/60492345/143024171-714ff23a-f3e0-4536-9e14-fe5b76d7d095.png)
and after 5 second it just say timeout
![image](https://user-images.githubusercontent.com/60492345/143024254-bf39c981-b77c-44b6-bc7b-33a3325229e5.png)
(im using sodium mod)

**Comment by hevav** [comment]
You've probably misconfigured the Velocity server, this problem is not related with LimboAPI

**Comment by Garuda2703** [comment]
hm what did i do wrong here?
[config1.txt](https://github.com/Elytrium/LimboAPI/files/7588157/config1.txt)
i also have geyser plugin
