### ISSUE TITLE
Auth server not working a remembering passwords to cracked players

### ISSUE THREAD

**Issue by megatron0001** [Elytrium/LimboAPI#2]
[18:28:49 ERROR]: [initial connection] /UR MOM:59063: exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl@3a675a7e
java.sql.SQLException: Unable to run insert stmt on object net.elytrium.limboauth.model.RegisteredPlayer@12cfeb3b: INSERT INTO `auth` (`nickname` ,`lowercaseNickname` ,`hash` ,`ip` ,`totpToken` ,`regdate` ) VALUES (?,?,?,?,?,?)
        at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:25) ~[?:?]
        at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:140) ~[?:?]
        at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:465) ~[?:?]
        at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:332) ~[?:?]
        at net.elytrium.limboauth.handler.AuthSessionHandler.register(AuthSessionHandler.java:198) ~[?:?]
        at net.elytrium.limboauth.handler.AuthSessionHandler.onChat(AuthSessionHandler.java:74) ~[?:?]
        at net.elytrium.limboapi.server.LimboSessionHandlerImpl.handle(LimboSessionHandlerImpl.java:88) ~[?:?]
        at com.velocitypowered.proxy.protocol.packet.Chat.handle(Chat.java:116) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.0.0]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity.jar:3.0.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[velocity.jar:3.0.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[velocity.jar:3.0.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[velocity.jar:3.0.0]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[velocity.jar:3.0.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity.jar:3.0.0]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.0.0]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.0.0]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_1 ON PUBLIC.AUTH(LOWERCASENICKNAME) VALUES 3"; SQL statement:
INSERT INTO `auth` (`nickname` ,`lowercaseNickname` ,`hash` ,`ip` ,`totpToken` ,`regdate` ) VALUES (?,?,?,?,?,?) [23505-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:459) ~[?:?]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:205) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:181) ~[?:?]
        at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103) ~[?:?]
        at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:221) ~[?:?]
        at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:196) ~[?:?]
        at org.h2.mvstore.db.MVTable.addRow(MVTable.java:531) ~[?:?]
        at org.h2.command.dml.Insert.insertRows(Insert.java:195) ~[?:?]
        at org.h2.command.dml.Insert.update(Insert.java:151) ~[?:?]
        at org.h2.command.CommandContainer.update(CommandContainer.java:198) ~[?:?]
        at org.h2.command.Command.executeUpdate(Command.java:251) ~[?:?]
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191) ~[?:?]
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152) ~[?:?]
        at com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:193) ~[?:?]
        at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:92) ~[?:?]
        ... 43 more

**Comment by mdxd44** [comment]
![picture](https://user-images.githubusercontent.com/67416904/131203222-333090ad-b14c-4e1d-98ee-e61d5ea6eeb4.png)
bruh
