### ISSUE TITLE
Couldn't pass GameProfileRequestEvent to limboapi

### ISSUE THREAD

**Issue by JulianN97** [Elytrium/LimboAPI#27]
Velocity version: 3.1.0
I am using auth, filter and api
Java version 16 or 17 i have tested on both
Logs that appear on every join:
```
Couldn't pass GameProfileRequestEvent to limboapi
java.lang.IllegalArgumentException: Can not set final com.velocitypowered.proxy.connection.MinecraftConnection field com.velocitypowered.proxy.connection.client.InitialInboundConnection.connection to com.velocitypowered.proxy.connection.client.LoginInboundConnection
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:419) ~[?:?]
        at net.elytrium.limboapi.injection.login.LoginListener.hookLoginSession(LoginListener.java:134) ~[?:?]
        at net.elytrium.limboapi.injection.login.Lmbda$21.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.0.jar:3.1.0]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.0.jar:3.1.0]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.0.jar:3.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by mdxd44** [comment]
> Velocity version: 3.1.0 I am using auth, filter and api Java version 16 or 17 i have tested on both Logs that appear on every join:
> 
> ```
> Couldn't pass GameProfileRequestEvent to limboapi
> java.lang.IllegalArgumentException: Can not set final com.velocitypowered.proxy.connection.MinecraftConnection field com.velocitypowered.proxy.connection.client.InitialInboundConnection.connection to com.velocitypowered.proxy.connection.client.LoginInboundConnection
>         at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
>         at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
>         at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
>         at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
>         at java.lang.reflect.Field.get(Field.java:419) ~[?:?]
>         at net.elytrium.limboapi.injection.login.LoginListener.hookLoginSession(LoginListener.java:134) ~[?:?]
>         at net.elytrium.limboapi.injection.login.Lmbda$21.execute(Unknown Source) ~[?:?]
>         at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.0.jar:3.1.0]
>         at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.0.jar:3.1.0]
>         at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.0.jar:3.1.0]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
>         at java.lang.Thread.run(Thread.java:831) [?:?]
> ```

https://www.spigotmc.org/resources/limboapi-limboauth-limbofilter.95748/update?update=433432
