### ISSUE TITLE
[BUG] Did not find a valid velocity-plugin.json

### ISSUE THREAD

**Issue by comendantmc** [Elytrium/LimboAPI#42]
**Describe the bug**
LimboAPI doesn't start because of the error

```
[16:26:16 ERROR]: Unable to load plugin plugins/limboapi-1.0.4-SNAPSHOT.jar
com.velocitypowered.api.plugin.InvalidPluginException: Did not find a valid velocity-plugin.json.
  at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity.jar:3.1.1]
  at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:92) ~[velocity.jar:3.1.1]
  at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:324) ~[velocity.jar:3.1.1]
  at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:222) ~[velocity.jar:3.1.1]
  at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.1]
[16:26:16 ERROR]: Can't load plugin limboauth due to missing dependency limboapi
[16:26:16 ERROR]: Can't load plugin limbofilter due to missing dependency limboapi
```

**Server Info:**
 - LimboAPI Version - built by myself from the [latest commit](https://github.com/Elytrium/LimboAPI/commit/33cfd90b6e0cbc425f22203a03e74761096d7838)
 - /velocity dump link - https://dump.velocitypowered.com/hekayizuxi.json

**Comment by hevav** [comment]
You don't need to install the jar file from the "api/build" directory on your server
You need to install the jar file from the "plugin/build" directory instead
