### ISSUE TITLE
[BUG] Schematic World isn't loading due to ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by RiceCX** [Elytrium/LimboAPI#48]
**Describe the bug**
The world isn't loading due to an array index out of bounds error.

**To Reproduce**
1. Set a schematic in config
2. Restart server
3. See error

**Expected behavior**
For it to load the map.

**Screenshots**
Stack trace:
```c
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at net.elytrium.limboapi.api.file.SchematicFile.toWorld(SchematicFile.java:62) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:266) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:149) ~[?:?]
        at net.elytrium.limboauth.Lmbda$6.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-f0ea638f-b122)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-f0ea638f-b122)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-f0ea638f-b122)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Server Info (please complete the following information):**
All Limbo plugins versions:

-  LimboAPI 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/runs/5630619580
-  LimboAuth 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAuth/runs/5618221017

 - /velocity dump link https://dump.velocitypowered.com/ekoxilafah.json

**Additional context**
The schematic map can be downloaded here: https://www.dropbox.com/s/ue4jt2som2uzxff/LoginMap.schematic?dl=0

**Comment by RiceCX** [comment]
In FAWE I'm getting errors that I cannot save it in the mcedit format, is there another way to convert it?

```c
java.io.IOException: The formats `.schematic`, `.mcedit` and `.mce` are discontinued on versions newer than 1.12 and superseded by the sponge schematic implementation known for `.schem` files.
        at com.sk89q.worldedit.extent.clipboard.io.BuiltInClipboardFormat$2.getWriter(BuiltInClipboardFormat.java:110) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicSaveTask.call(SchematicCommands.java:882) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicSaveTask.call(SchematicCommands.java:777) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar:?]
        at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:154) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-31.0.1-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by hevav** [comment]
The only way I've tested is to install Spigot 1.12.2, and save the MCEdit schematic there.
I think it is possible to get a MCEdit schematic without Spigot 1.12.2, but I don't know how to do it.
