### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by volhw** [Elytrium/LimboAPI#53]
[02:21:53 ERROR]: Unable to load plugin plugins/limbofilter-1.0.4-SNAPSHOT.jar
com.velocitypowered.api.plugin.InvalidPluginException: Did not find a valid velocity-plugin.json.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:92) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:342) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:223) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-3ae93875-b138)]

velocity-3.1.1-98  java17.0.1" 2021-10-19 LTS

**Comment by volhw** [comment]
auth and api works

**Comment by hevav** [comment]
Re-download the limbofilter plugin
