### ISSUE TITLE
[BUG] Can't create plugin limboapi

### ISSUE THREAD

**Issue by puritynetwork** [Elytrium/LimboAPI#71]
[limboapi]: Initializing Simple Virtual Block system...
[13:23:24 INFO] [limboapi]: Initializing Simple Virtual Item system...
[13:23:24 INFO] [limboapi]: Hooking into EventManager, PlayerList and StateRegistry...
[13:23:24 ERROR]: Can't create plugin limboapi
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/PlayerListItem
  at LimboAPI.<init>(LimboAPI.java:146)
  at VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating LimboAPI

Learn more:
  ![Immagine 2022-12-11 143332](https://user-images.githubusercontent.com/120317607/206906682-45296ca3-1f41-49c3-bfa9-395300cf8f5a.png)

1 error

======================
Full classname legend:
======================
LimboAPI:             "net.elytrium.limboapi.LimboAPI"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
Caused by: java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/PlayerListItem
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:555) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:67) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:61) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.<init>(LimboAPI.java:171) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$846487.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$846487.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.PlayerListItem
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:84) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:61) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:555) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:67) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:61) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.<init>(LimboAPI.java:171) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$846487.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$846487.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        ... 6 more
[13:23:24 ERROR]: Can't create plugin limboauth
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboAuth.<init>(LimboAuth.java:164)
  at VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating LimboAuth

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
LimboAuth:              "net.elytrium.limboauth.LimboAuth"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:382) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.<init>(LimboAuth.java:174) ~[?:?]
        at net.elytrium.limboauth.LimboAuth$$FastClassByGuice$$1504521.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboauth.LimboAuth$$FastClassByGuice$$1504521.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        ... 6 more
[13:23:24 ERROR]: Can't create plugin limbofilter
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboFilter.<init>(LimboFilter.java:117)
  at VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating LimboFilter

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
LimboFilter:            "net.elytrium.limbofilter.LimboFilter"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:382) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.<init>(LimboFilter.java:126) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter$$FastClassByGuice$$2954811.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter$$FastClassByGuice$$2954811.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[velocity.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        ... 6 more

**Comment by JNNGL** [comment]
Update limboapi

**Comment by hevav** [comment]
Update LimboAPI to 1.0.7 version
1.0.6 version doesn't support Minecraft 1.19.3
