### ISSUE TITLE
[BUG] Exception during heavy bot attack

### ISSUE THREAD

**Issue by Wruczek** [Elytrium/LimboAPI#83]
**Describe the bug**
During a heavy bot attack, the following exceptions can be seen in Velocity logs:
```
[Netty epoll Worker #15/WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.elytrium.limboapi.server.LimboImpl$$Lambda$2520/0x00000008015e9870@15db9198
java.lang.NullPointerException: Cannot invoke "com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.setState(com.velocitypowered.proxy.protocol.StateRegistry)" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
	at com.velocitypowered.proxy.connection.MinecraftConnection.setState(MinecraftConnection.java:353) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
	at net.elytrium.limboapi.server.LimboImpl.lambda$spawnPlayer$6(LimboImpl.java:233) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**To Reproduce**
View the console during heavy bot attack with bots that join and leave the server after a few seconds.

**Expected behavior**
No exception

**Screenshots**
None

**Server Info (please complete the following information):**
- LimboAPI 1.1.11 downloaded from GitHub releases
- LimboAuth 1.1.12 downloaded from GitHub releases
- LimboFilter 1.1.10 downloaded from GitHub releases

**Additional context**
None

**Comment by hevav** [comment]
Send me /velocity dump

**Comment by Wruczek** [comment]
<details>
  <summary>/velocity dump output</summary>
(Some information was redacted.)

```json
{
  "versionInfo": {
    "name": "Velocity",
    "vendor": "Velocity Contributors",
    "version": "3.2.0-SNAPSHOT (git-01f1e1a9-b243)"
  },
  "platform": {
    "operatingSystemType": "Linux",
    "operatingSystemVersion": "5.4.65-1-pve",
    "operatingSystemArchitecture": "amd64",
    "javaVersion": "17.0.6",
    "javaVendor": "Eclipse Adoptium",
    "listener": {
      "listenerType": "epoll",
      "compression": "libdeflate (Linux x86_64)",
      "encryption": "OpenSSL 3.0.x (Linux x86_64)"
    }
  },
  "config": {
    "bind": "0.0.0.0:0",
    "motd": "x",
    "showMaxPlayers": 1,
    "onlineMode": false,
    "preventClientProxyConnections": false,
    "playerInfoForwardingMode": "LEGACY",
    "announceForge": false,
    "onlineModeKickExistingPlayers": false,
    "pingPassthrough": "DISABLED",
    "advanced": {
      "compressionThreshold": 512,
      "compressionLevel": -1,
      "loginRatelimit": 3000,
      "connectionTimeout": 5000,
      "readTimeout": 30000,
      "proxyProtocol": true,
      "tcpFastOpen": true,
      "bungeePluginMessageChannel": false,
      "showPingRequests": false,
      "failoverOnUnexpectedServerDisconnect": false,
      "announceProxyCommands": false,
      "logCommandExecutions": false,
      "logPlayerConnections": true
    },
    "query": {
      "queryEnabled": false,
      "queryPort": 25577,
      "queryMap": "Velocity",
      "showPlugins": false
    },
    "enablePlayerAddressLogging": true,
    "forceKeyAuthentication": false,
    "servers": {
      "lobby": {
        "currentPlayers": 0,
        "host": "XXX.XXX.XXX.XXX",
        "port": 0
      },
      "server": {
        "currentPlayers": 0,
        "host": "XXX.XXX.XXX.XXX",
        "port": 0
      }
    },
    "connectOrder": [
      "lobby"
    ],
    "forcedHosts": {}
  },
  "plugins": [
    {
      "id": "limboapi",
      "name": "LimboAPI",
      "version": "1.1.11",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "Velocity plugin for making virtual servers.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboauth",
      "name": "LimboAuth",
      "version": "1.1.12",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi",
        "floodgate"
      ]
    },
    {
      "id": "limbofilter",
      "name": "LimboFilter",
      "version": "1.1.10",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi"
      ]
    },
    {
      "id": "luckperms",
      "name": "LuckPerms",
      "version": "5.4.58",
      "authors": [
        "Luck"
      ],
      "description": "A permissions plugin",
      "url": "https://luckperms.net"
    },
    {
      "id": "skinsrestorer",
      "name": "SkinsRestorer",
      "version": "14.2.5",
      "authors": [
        "knat",
        "AlexProgrammerDE",
        "Blackfire62",
        "McLive"
      ],
      "description": "Ability to restore/change skins on servers! (Offline and Online Mode)",
      "url": "https://skinsrestorer.net/"
    }
  ]
}
```

</details>
