### ISSUE TITLE
[BUG] Broken compatibility with Viaversion

### ISSUE THREAD

**Issue by kuzuanpa** [Elytrium/LimboAPI#95]
**Describe the bug**
Broken compatibility with Viaversion, when player damaged by somebody, He will be kick from server.

**To Reproduce**
1. Install plugins
2. summon a zombie, let he hit you
3. you will be kick.

**Expected behavior**
Player won't be kick

**Screenshots**

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.1.13 
 - LimboAuth 1.1.12
 - LimboFliter 1.1.10

All from github Release

 - /velocity dump link 
[velocity-dump-2023-06-11-00-46-21.json.txt](https://github.com/Elytrium/LimboAPI/files/11712877/velocity-dump-2023-06-11-00-46-21.json.txt)
**Additional context**
See https://github.com/ViaVersion/ViaVersion/issues/3334

**Comment by JNNGL** [comment]
Don't use ViaVersion on proxy

**Comment by kuzuanpa** [comment]
...Good solution, At least worse a try.

**Comment by Kamillaova** [comment]
rm ViaVersion*.jar.

**Comment by EnchStudio** [comment]
another bug with viaproxy
when join the limbo
I need to use viaversion, deleting it is unrealistic
```
[09:08:35] [Netty Epoll Client IO #0/WARN] (ViaVersion) ERROR IN Protocol1_19_4To1_20 IN REMAP OF CHUNK_DATA (0x24)                                                                                    
[09:08:35] [Netty Epoll Client IO #0/ERROR] (ViaProxy) Caught unhandled netty exception                                                                                                                
 io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository   
Packet Type: CHUNK_DATA, Type: Chunk, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.BlockItemPackets1_20$1 (Anonymous), Packet ID: 36                
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                     
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                    
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                        
        at net.raphimc.vialoader.netty.ViaCodec.channelRead(ViaCodec.java:81) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                                        
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                    
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                    
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                        
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                    
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                     
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                    
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                        
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                    
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                    
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                        
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                    
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                         
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                  
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                  
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                                        
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                              
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                                 
        at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CHUNK_DATA, Type: Chunk, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.BlockItemPackets1_20$1 (Anonymous), Packet ID: 36
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(6435) + length(8) exceeds writerIndex(6437): PooledUnsafeDirectByteBuf(ridx: 6435, widx: 6437, cap: 6437)                                  
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]      
        at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]    
        at com.viaversion.viaversion.api.type.types.LongArrayType.read(LongArrayType.java:39) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                        
        at com.viaversion.viaversion.api.type.types.LongArrayType.read(LongArrayType.java:28) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                                                     
        at com.viaversion.viaversion.api.type.types.version.PaletteType1_18.read(PaletteType1_18.java:53) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                                            
        at com.viaversion.viaversion.api.type.types.version.ChunkSectionType1_18.read(ChunkSectionType1_18.java:47) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.protocol1_18to1_17_1.types.Chunk1_18Type.read(Chunk1_18Type.java:56) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.protocol1_18to1_17_1.types.Chunk1_18Type.read(Chunk1_18Type.java:34) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:145) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:191) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]     
        at com.viaversion.viaversion.rewriter.BlockRewriter.lambda$chunkDataHandler1_19$0(BlockRewriter.java:174) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]  
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]        
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]            
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]        
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]        
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at net.raphimc.vialoader.netty.ViaCodec.decode(ViaCodec.java:57) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                        
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]        
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[ViaProxy-3.0.20-SNAPSHOT.jar:?]                   
        ... 36 more                                                                                                                                                                                    
[09:08:35] [Netty Epoll Client IO #0/ERROR] (ViaProxy) [KICK] (127.0.0.1 | BLT) An unhandled error occurred in your connection and it has been closed.
Error details for report:                                                                                                                                                                              
InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository             
Packet Type: CHUNK_DATA, Type: Chunk, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.BlockItemPackets1_20$1 (Anonymous), Packet ID: 36 Caused by
IndexOutOfBoundsException: readerIndex(6435) + length(8) exceeds writerIndex(6437): PooledUnsafeDirectByteBuf(ridx: 6435, widx: 6437, cap: 6437)
```

**Comment by Kamillaova** [comment]
@EnchStudio @kuzuanpa for now, this issue is wontfix

**Comment by kuzuanpa** [comment]
@Kamillaova I've mv all Via* plugins to backend servers and works well.
And I think whether this issue should be closed as not planned should be decided by developers.
